spring.cloud.gateway.routes:
  - id: test1
    uri: http://httpbin.org/
    predicates:
      - Path=/get2
    filters:
      - AddRequestHeader=X-Request-red, blue
      - SetPath=/anything
      - My

server:
  port: 8080


management:
  endpoint:
    gateway.enabled: true

  endpoints:
    web:
      exposure:
        include: "*"



spring:
  cloud:
    gateway:
      metrics:
        enabled: true
