logging.level.org.springframework.cloud.gateway: TRACE

spring.cloud.gateway:
  metrics:
    enabled: true
  routes:
    - id: test1
      uri: http://httpbin.org/
      predicates:
        - Path=/get2
      filters:
        - AddRequestHeader=X-Request-red, blue
        - SetPath=/anything
        - My
    - id: ws-test
      uri: ws://localhost:9000
      predicates:
        - Path=/echo

server:
  port: 8080

management:
  endpoints.web.exposure.include: route, health, info
  endpoint.gateway.enabled: false # 默认为false
  metrics.tags:
    application: "san-test-gateway"


