### test get
GET http://localhost:8080/get
Accept: application/json

### test get2
GET http://localhost:8080/get2
Accept: application/json

### test get2-json
GET http://localhost:8080/get2?foo=bar
Content-Type: application/json

{
  "hei":"har"
}

### test get2-formurl
GET http://localhost:8080/get2?foo=bar
Content-Type: application/x-www-form-urlencoded

id=999&value=content




### test .circuit breaker
GET http://localhost:8080/delay/3
Host: www.circuitbreaker.com

> {%
client.test("Request executed fail", function() {
  client.assert(response.status === 504, "Response status is not 504");
});
%}

### test .circuit breaker with fallback
GET http://localhost:8080/delay/3
Host: www.circuitbreaker2.com

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.body.toString() === "fallback", "body is not fallback");
});
%}

### saveroute
POST http://127.0.0.1:8080/route/save
Content-Type: application/json

{
  "id" : "routeMem1",
  "uri" : "http://httpbin.org/",
  "order" : 3,
  "predicates" : [ {
    "name" : "Path",
    "args" : {
      "_genkey_0" : "/get3"
    }
  } ],
  "filters" : [ {
    "name" : "SetPath",
    "args" : {
      "_genkey_0" : "/anything"
    }
  } ]
}

### get route list
GET http://127.0.0.1:8080/route/list


### test get2
GET http://localhost:8080/get3
Accept: application/json

